### ISSUE TITLE
EPIC: Automations for increased WG productivity and visibility

### ISSUE THREAD

**Issue by carlisia** [knative/community#1061]
As a maintainer for Knative, I appreciate all the existing working group automations that the project either has documented somewhere, or that existing maintainers are willing to share.

This EPIC lists tasks with improvements to the existing workflow of generating and viewing WG updates.

- Slack: since every working group has a corresponding Slack channel, and [we already have infra](https://github.com/knative-sandbox/knobots/blob/main/README.md#welcome-to-knobots) to post to Slack, this would be an obvious choice.
- a permanent file in the `community` repo with an aggregate of all WGs
- the Knative Twitter account
- the dev mailing list

## Tasks with outputs per WG 
For each of the tasks, the following needs to be considered:
- clean up/improve/replace/create script
- for Slack channel output, ensure output is grouped by WG and is sent only to the corresponding WG channel
- use the [existing infra](https://github.com/knative-sandbox/knobots#adding-new-automation), and decide on the job run frequency

Consider approaching this solution as a system, looking for opportunities to extract pieces that can be reused

- [ ] TOC schedule for WG review/update. 
	- notes:
		- there is an [`awk` command](https://github.com/knative/community/blob/main/mechanics/TOC-REVIEW.schedule) that generates a list  with dates for each even.
		- TBD: the source script that outputs the schedule that is currently manually added to the page
- [ ] List contributions on a per monthly basis for the last x (3?) months
	- monitor contributor engagement in general
	- surface who is on track for approver and who is on track for lead. Note: the above metric of PRs merged is only 1 aspect of consideration for being an approver and lead
	- notes:
		- the script used by the [Networking WG](https://gist.github.com/nak3/36d7a871e5b14370fdfdde284481f76a). 
		- should exclude automation accounts
- [ ] [support rotation ](https://github.com/knative/community/issues/402)

/Epic
