### ISSUE TITLE
PROCESS CHANGE: Extended Docs WG roadmap process

### ISSUE THREAD

**Issue by abrennan89** [knative/community#1141]
**Proposal doc: https://docs.google.com/document/d/1_UWBJA_cuZnhavQJ0gGFGF-5JtsrCG8C8p9mCBbT6es/edit#heading=h.n8a530nnrb**

**Exit Criteria**

- [ ] The extended Docs WG roadmap process is agreed upon and documented in a new section for WG processes under https://github.com/knative/docs/tree/main/contribute-to-docs 
- [ ] Each non-Docs WG includes a link to the extended Docs WG roadmap process in their process documentation so that this is visible.
- [ ] Epic templates are created by the Docs WG that include all of the information that we need to work on a new documentation project.
- [ ] Agreement to the process from all non-Docs WGs.
- [ ] Approval by the TOC to implement the new process.

**Expected benefits:** Outlined in doc.

**Expected costs:**

   * Other WG leads provide input to the Docs WG about documentation requirements for their area of expertise.
   * Quarterly documentation audits are carried out by non-Docs WGs to review existing documentation and provide information about content that can be deprecated, removed, or updated.
   * Each non-Docs WG provides documentation requirements for each new feature or feature change as part of their pull request template.
   * Each non-Docs WG includes a link to the extended Docs WG roadmap process in their process documentation so that this is visible.
* No real costs other than what should be a reasonable time investment from other WGs.

**_Process can in part be driven by the docs WG, however we are requesting that other WGs take on and agree to deliver on the above mentioned responsibilities._**

**Comment by evankanderson** [comment]
Other discussion:

* GitHub recently added new features to the README format
* We could (should?) enable GitHub pages for repos, particularly in `-sandbox`, so that they can maintain first-class documentation on a separate domain without needing to go into `knative/docs`.

**Comment by dprotaso** [comment]
cc @knative/ux-wg-leads unsure if you've seen this proposal or not

Given this was created by the prior Docs WG Lead I think it's worth removing this off the TOC backlog for now and letting you folks decide if this is something you would still want to pursue and rework the asks

/assign @Cali0707 
/assign @zainabhusain227 
/assign @mmejia02 
/assign @Leo6Leo

**Comment by Cali0707** [comment]
Hey @dprotaso I think that since the UX WG is currently trying to only focus on UX and not Docs, we won't be pursuing this in our group for now. Should we close this?
