### ISSUE TITLE
Adjust TOC meeting frequency to every other week

### ISSUE THREAD

**Issue by psschwei** [knative/community#1314]
In today's (March 16) TOC meeting, we decided to adjust the frequency to biweekly (every other week), beginning the week of April 27. 

### Tasks

* [x] announce on user / dev mailing groups
* [x] adjust google calendar
* [ ] update review schedule

/assign

**Comment by zroubalik** [comment]
@dsimansk yeah, the new schedule should start at the end of April (after KubeCon)
