### ISSUE TITLE
Epic: Setting up the UX Working Group

### ISSUE THREAD

**Issue by csantanapr** [knative/community#466]
The new proposal for the new UX Working Group got accepted by the TOC.

We followed the process [Proposing a new Working Grooup](https://github.com/knative/community/blob/master/mechanics/WORKING-GROUP-PROCESSES.md#proposing-a-new-working-group)

The [New UX WG Proposal](https://github.com/knative/community/issues/420) got accepted by TOC

This issue tracks [Setting up a working group](https://github.com/knative/community/blob/master/mechanics/WORKING-GROUP-PROCESSES.md#setting-up-a-working-group) Tasks:

- [x] **Create a Google Drive Folder**. Create a folder to hold your working group
  documents within this parent
  [folder](https://drive.google.com/drive/folders/0AM-QGZJ-HUA8Uk9PVA).
  Call your folder "User Experience".
- [x] **Create a Meeting Notes Document**. Create a blank document in the above
  folder and call it "User Experience Group Meeting Notes [shared externally]".
- [x] **Create a Roadmap Document**. Create a document in the above folder and call
  it "GROUP_NAME Group Roadmap". Put your initial roadmap in the document.
- [x] **Schedule a Recurring Meeting**. Create a recurring meeting (weekly or
  bi-weekly, 30 or 60 minutes) on the
  [shared calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)
  and call the meeting "\$GROUP_NAME WG". Attach the meeting notes document to
  the calendar event. Generally schedule these meetings between 9:00AM to 2:59PM
  Pacific Time. Invite `knative-dev@googlegroups.com` Google group to the
  meeting, as well as necessary individual participants.
- [x] **Register the Working Group**. Go to
  [WORKING-GROUPS.md](../working-groups/WORKING-GROUPS.md) and add your working
  group name, the names of the leads, the working group charter, and a link to
  the meeting you created.
- [x] **Create Github Team using Peribolos**. Go to
  [peribolos/knative.md](../peribolos/knative.md), add your working
  group name under teams, and members. Grant access to relevant repositories for the working group.
- [x] **Announce your Working Group**. Send a note to
  [knative-dev@](mailto:knative-dev@googlegroups.com),
  [knative-tech-oversight@](mailto:knative-tech-oversight@googlegroups.com), and
  [steering@](mailto:steering@knative.team) to
  announce your new working group. Include your charter in the email and provide
  links to the meeting invitation.

In addition to UX WG, we will set up the following tasks

- [x] New github repo knative/ux  This repo will be use to create Projects at the ux repo level to track epics/areas, and one at the org level that can be use to track roadmap
- [x] Projects,  One org Project UX WG that will serve as roadmap tracker, projects at the ux repo level

**Comment by csantanapr** [comment]
>  Create a Google Drive Folder. Create a folder to hold your working group
documents within this parent
folder.
Call your folder "User Experience".

New folder [User Experience](https://drive.google.com/drive/folders/1XzZGqV7yHo38d_l7rH1uSIrbQp3JlbBP?usp=sharing) created

**Comment by csantanapr** [comment]
>Create a Meeting Notes Document. Create a blank document in the above
folder and call it "User Experience Group Meeting Notes [shared externally]".

The document is now created and shared externally [User Experience Group Meeting Notes [shared externally]](https://docs.google.com/document/d/1NSlGHen5Dh6c2A0LGavGWibddWrlSLV_PbEbMpNjSTU/edit?usp=sharing)

**Comment by omerbensaadon** [comment]
>Schedule a Recurring Meeting.
Done!

**Comment by csantanapr** [comment]
Submitted PR to update WORKING-GROUPS.md 
https://github.com/knative/community/pull/472

**Comment by csantanapr** [comment]
@omerbensaadon I don't see the calendar entry for the wg meeting here https://calendar.google.com/calendar/u/0/embed?src=knative.team_9q83bg07qs5b9rrslp5jor4l6s@group.calendar.google.com

**Comment by csantanapr** [comment]
PR to update Peribolos here https://github.com/knative/community/pull/473

**Comment by csantanapr** [comment]
PR to add ux repo https://github.com/knative/community/pull/476

**Comment by csantanapr** [comment]
> Schedule a Recurring Meeting. Create a recurring meeting (weekly or
bi-weekly, 30 or 60 minutes) on the
shared calendar
and call the meeting "$GROUP_NAME WG". Attach the meeting notes document to
the calendar event. Generally schedule these meetings between 9:00AM to 2:59PM
Pacific Time. Invite knative-dev@googlegroups.com Google group to the
meeting, as well as necessary individual participants.

The meeting is located on Knative.team calendar now Thursdays 8AM PST https://knative.dev/community/calendar/

**Comment by csantanapr** [comment]
>Create Github Team using Peribolos. Go to
peribolos/knative.md, add your working
group name under teams, and members. Grant access to relevant repositories for the working group.

Github team created @knative/ux-wg-leads @knative/ux-writers

**Comment by csantanapr** [comment]
>New github repo knative/ux This repo will be use to create Projects at the ux repo level to track epics/areas, and one at the org level that can be use to track roadmap

New git repo here https://github.com/knative/ux

**Comment by csantanapr** [comment]
> Projects, One org Project UX WG that will serve as roadmap tracker, projects at the ux repo level

Top-level Project at org level located here  https://github.com/orgs/knative/projects/20

**Comment by csantanapr** [comment]
>Register the Working Group. Go to
WORKING-GROUPS.md and add your working
group name, the names of the leads, the working group charter, and a link to
the meeting you created.

WG info located here https://github.com/knative/community/blob/master/working-groups/WORKING-GROUPS.md#user-experience

**Comment by csantanapr** [comment]
> Create a Roadmap Document. Create a document in the above folder and call
it "GROUP_NAME Group Roadmap". Put your initial roadmap in the document.

UX Working group is going unconventional 😄 

Document created in drive [Slide UX WG Roadmap](https://docs.google.com/presentation/d/1e-8yG9O35QV7HQoCAG0d_a4tx-AH6-okSjlBgJQ5fs8/edit?usp=sharing), but it is s a snapshot of the live Roadmap being done in [Github Project UX WG Roadmap](https://github.com/orgs/knative/projects/20)

**Comment by csantanapr** [comment]
> Announce your Working Group. Send a note to
knative-dev@,
knative-tech-oversight@, and
steering@ to
announce your new working group. Include your charter in the email and provide
links to the meeting invitation.

The announcement message was sent to all emails and slack

**Comment by csantanapr** [comment]
Marking this issue close. 
Thank you @evankanderson @rhuss @mattmoor for reviewing and merging PRs
Thank you @omerbensaadon for assistance on tasks

/close

**Comment by csantanapr** [comment]
All the information for the new UX WG can be found on the site https://knative.dev/community/contributing/working-groups/working-groups/#user-experience

**Comment by omerbensaadon** [comment]
@csantanapr legend!!! Thank you for taking care of this 🥳
